<?php


$title = 'Delete page';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete the page
    '<?php echo $this->escapeHtml($page->title); ?>' 
    '<?php echo $this->escapeHtml($page->text); ?>'?
</p>
<?php
$url = $this->url('page', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $page->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>

