<html>
<head>
<?php

$title = 'My pages';
$this->headTitle($title);
//print_r($pages);
?>


<link href="http://site.jj/bootstrap/bootstrap-3.0.0/dist/css/bootstrap.css" media="screen" rel="stylesheet" type="text/css">

<link href="http://site.jj/bootstrap/bootstrap-3.0.0/dist/css/bootstrap-theme.min.css" media="screen" rel="stylesheet" type="text/css">
<link href="/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">
                <!-- Scripts -->
<script type="text/javascript" src="/js/jquery.min.js"></script>
<!--<script type="text/javascript" src="http://johnny.github.io/jquery-sortable/js/jquery-sortable.js"></script>-->
<script type="text/javascript" src="http://site.jj/bootstrap/bootstrap-3.0.0/dist/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/bootstrap/js/bootstrap-carousel.js"></script>
<script type="text/javascript" src="http://site.jj/bootstrap/bootstrap-3.0.0/js/modal.js"></script>
<script type="text/javascript" src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<!--[if lt IE 9]><script type="text/javascript" src="/js/html5.js"></script><![endif]-->
<link href="http://site.jj/bootstrap-editable/css/bootstrap3-editable.css" rel="stylesheet">
<script type="text/javascript" src="http://site.jj/bootstrap-editable/js/bootstrap3-editable.js"></script>

    	

        <script type="text/javascript">
            $('.carousel').carousel();
            $('.carousel').carousel('pause');
        </script>
        
<style>
.input-xlg {  
  height: 60px;
  width: 100%;
  padding: 10px 16px;
  font-size: 30px;
  line-height: 1.33;
  border-radius: 6px;
}

</style>

</head>
<body>
	
	<input class="form-control" id="focusedInput" type="text" value="This is focused...">

	
<div class="col-lg-12">
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	
	<a data-toggle="modal" href="#addPage" class="btn btn-primary btn-lg" style="position : fix; left : 20px; top :10px;"><span class="glyphicon glyphicon-plus"></span> Add new page</a>


    
</p>

<div class="tabbable">
<div class='span12'>
    <ul id="navigation" class="nav nav-pills">
        <?php $count = 0; ?>        
        <?php foreach ($tabs as $tab) : ?>
            <?php if ($count == 0) : ?>
                <li class="active"><a href="#<?php echo $this->escapeHtml($tab->name); ?>Tab" data-toggle="pill"><span><?php echo $this->escapeHtml($tab->title); ?></span></a></li>
            <?php else : ?>
                <li><a href="#<?php echo $this->escapeHtml($tab->name); ?>Tab" data-toggle="pill"><span><?php echo $this->escapeHtml($tab->title); ?></span></a></li>
            <?php endif; ?>
            <?php $count++; ?>
        <?php endforeach; ?>

    </ul>
</div>
<br />
<div class="tab-content">
        <?php $pageCount = 0; ?>
        <?php foreach ($pages as $page) : ?>
            <?php if ($pageCount == 0) {
                $paneAddClass = ' active';
            } else {
                $paneAddClass = '';
            }
            ?>
                <div class="tab-pane<?php echo $paneAddClass; ?>" id="<?php echo $this->escapeHtml($page['name']); ?>Tab">
                    <?php $pageCount++; ?>
                    <div class="main-content-container">
                        <div class="main-content">
                        	<p>
                        	<a data-toggle="modal" class="btn btn-warning" href="#config-<?php echo $page['name'];?>"><span class="glyphicon glyphicon-cog"></span> Config page</a>
							<a class="btn btn-danger" href="#"><span class="glyphicon glyphicon-trash"></span> Delete</a>
							</p>
                            <?php if ($page['contentCount'] == 1) : ?>
                                <div class="single-content row-fluid" id="<?php echo $this->escapeHtml($page['name']); ?>Content">
                                    <div class="row">
                                    <div class="col-md-6">
                                    	<div class="panel panel-info">
                                    		<div class="panel-heading" style="position : relative; overflow:hidden;">
                                    			Title    			
		    									<a href="#" class="edit-pencil"><span class="glyphicon glyphicon-pencil" style="position : absolute; right : 20; top :-20px;"></span></a>
                                    		</div>
                                    		<div class="panel-body">
                                    			<div class="changeable" data-toggle="manual" data-name="title" data-type="text" data-pk="<?php echo $this->escapeHtml($page['contents'][0]['id']);?>" data-url="/page/editable">
                                    			<?php echo $this->escapeHtml($page['contents'][0]['title']); ?>
                                    			</div>
                                        	</div>
                                        </div>
                                        <div class="panel panel-info">
                                        	<div class="panel-heading" style="position : relative; overflow:hidden;">
                                        		Text
                                        		<a href="#" class="edit-pencil"><span class="glyphicon glyphicon-pencil" style="position : absolute; right : 20; top :-20px;"></span></a>
                                        		
                                        	</div>
                                    		<div class="panel-body">
                                       			<div class="changeable" data-toggle="manual" data-name="text" data-type="textarea" data-pk="<?php echo $this->escapeHtml($page['contents'][0]['id']);?>" data-url="/page/editable">
												<?php echo $this->escapeHtml($page['contents'][0]['text']); ?>
												</div>
   											</div>
   										</div>
                                     </div>
                                        <div class="col-md-6">
                                            <div class="panel panel-info">
                                            	<div class="panel-heading" style="position : relative; overflow:hidden;">
                                            		Image
                                            		<span style="position : absolute ; right: 20; top:-20px" class="glyphicon glyphicon-pencil">
													</span>
												</div>
                                            	<div class="panel-body">
                                                <img class="col-md-12" src="../img/<?php echo $this->escapeHtml($page['contents'][0]['img']); ?>">
												</div>
                                            </div>
                                        </div>
                                    
                                    </div>
                                </div>
                            <?php else : ?>
                                <div class="carousel slide row-fluid" id="<?php echo $this->escapeHtml($page['name']); ?>Carousel">
                                    <div class='span12'>
                                    
                                            <div class="span6 carousel-control-wrapper">
                                                <ol class="carousel-indicators">
                                                    <?php $count = 1; ?>
                                                    <?php while ($count <= $page['contentCount']) : ?>
                                                    	<?php if($count == 1) : ?>
                                                    		<li data-target="#<?php echo $this->escapeHtml($page['name']); ?>Carousel" data-slide-to="<?php echo $this->escapeHtml($count - 1); ?>" class="active"><?php echo $this->escapeHtml($count); ?></li>
                                                    	<?php else : ?>	
                                                        	<li data-target="#<?php echo $this->escapeHtml($page['name']); ?>Carousel" data-slide-to="<?php echo $this->escapeHtml($count - 1 ); ?>"><?php echo $this->escapeHtml($count); ?></li>
                                                        <?php endif;?>
                                                        <?php $count++; ?>
                                                    <?php endwhile; ?>
                                                </ol>
                                            </div>
                                            <div class="span6">

                                            </div>
                                        </div>
                                       
                                        <div class="carousel-inner row-fluid">
                                                <?php $count = 0; ?>
                                                <?php foreach ($page['contents'] as $content) : ?>
                                                <?php $defaultItemClass = ($count == 0) ? " active" : ""; ?>
                                                    <div class="item row-fluid<?php echo $defaultItemClass; ?>">
                                                     <?php $count ++; ?>
                                                        <div class="span6">
                                                            
                                                                <h4><?php echo $this->escapeHtml($content['label']) ?></h4>
                                                                <div><?php echo $this->escapeHtml($content['text']) ?></div>

                                                        </div>
                                                        <div class="span6">
                                                            <div class="thumbnail">	
  Title                                                               <img src="<?php $this->url(); ?>/img/<?php echo $this->escapeHtml($content['img']) ?>" alt="">
                                                            Title</div>
                                                        </div>                                           
                                                    </div>

                                                <?php endforeach; ?>
                                            </div>
                                            <a class="left carousel-control" href="#<?php echo $this->escapeHtml($page['name']); ?>Carousel" data-slide="prev">&lsaquo;</a>
                                            <a class="right carousel-control" href="#<?php echo $this->escapeHtml($page['name']); ?>Carousel" data-slide="next">&rsaquo;</a>
                                        
                                    </div>
                                <?php endif; ?>
                        </div>
                   	 </div>
                    </div>
                <?php endforeach; ?>	

        </div>
</div>
</div>
<?php foreach ($editPages as $editPage) : ?>
	
	<div class="modal fade" id="config-<?php echo $editPage->name;?>" tabindex="-1" role="dialog"  aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Config page</h4>
        </div>
        <div class="modal-body">
         
<table  class="table table-bordered table-striped">
        <tbody> 
            <tr>         
                <td width="40%">Page Title (Title in the Tabs)</td>
                <td><a href="#" class="changeable-page editable editable-click" data-pk="<?php echo $editPage->id;?>" data-type="text" data-name="title"><?php echo $editPage->title;?></a></td>
            </tr>
            <tr>         
                <td>Page Name (in one word)</td>
                <td><a href="#" class="changeable-page editable editable-click" data-pk="<?php echo $editPage->id;?>" data-type="text" data-name="name"><?php echo $editPage->name;?></a></td>
            </tr>
			<tr>
				<td>Choose page Template</td>
				<td><a href="#" class="template changeable-page editable editable-click" data-pk="<?php echo $editPage->id;?>" data-type="select" data-name="template" data-value="<?php echo $editPage->template;?>"></a></td>
			</tr>
	</tbody>
</table>
	
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" id="save-page">Save Page</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
	
	
<?php endforeach; ?>


<div class="modal fade" id="addPage" tabindex="-1" role="dialog" aria-labelledby="addPageLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Add a new page</h4>
        </div>
        <div class="modal-body">
         This is where x-editable will be placed...
<table  class="table table-bordered table-striped">
        <tbody> 
            <tr>         
                <td width="40%">Enter page Title (Title in the Tabs)</td>
                <td><a href="#" class="add-page editable editable-click editable-empty" data-type="text" data-name="title">Empty</a></td>
            </tr>
            <tr>         
                <td>Enter page Name (in one word)</td>
                <td><a href="#" class="add-page editable editable-click editable-empty" data-type="text" data-name="name">Empty</a></td>
            </tr>
			<tr>
				<td>Choose page Template</td>
				<td><a href="#" class="template add-page editable editable-click" data-type="select" data-name="template"></a></td>
			</tr>
	</tbody>
</table>
	
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" id="add-page">Add Page</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
	
	


<script type="text/javascript">
$(document).ready(function() {
    $('#control-panel a:first').tab('show');

		$('.template').editable({
		url: '/page/save',
    	value: 1,
    	source: [
        		    {value: 1, text: 'Single Page'},
        		    {value: 2, text: 'Carousel Page'},
        		    {value: 3, text: 'Custom Page'}
        		]
        });
    	
    	$('.add-page').editable({
		url: 'http://site.jj/page/save' //this url will not be used for cxreating new user, it is only for update
		});	
		$('.changeable-page').editable({
		url:'http://site.jj/page/save'
		});
		$('.template').editable({
		url:'http://site.jj/page/save'
		});
   		
   		$('#add-page').click(function() {
    	$('.add-page').editable('submit', {
    	url: '/page/add',
    	ajaxOptions: {
    	dataType: 'json' //assuming json response
    	},
    	success: function(data, config) {
    	if(data && data.id) { //record created, response like {"id": 2}
    	//set pk
    	$(this).editable('option', 'pk', data.id);
    	//remove unsaved class
    	$(this).removeClass('editable-unsaved');
    	//show messages
    	var msg = 'New Page created! Now submit individually.';
    	$('#msg').addClass('alert-success').removeClass('alert-error').html(msg).show();
    	$('#add-page').hide();
    	$(this).off('save.newuser');
    	var page = $(this).editable('getValue');
    	alertMsg = 'this is the name:'+page.name+' this is the title:'+page.title+' and this is the tmplate number:'+page.template;
    	alert(alertMsg);
    	/* 
    	 *$('.blablabla').append()
    	 *var newTabHTML =   'new tab button done
    	 *					new empty tab container{
    	 *					new config button I.E. edit and delete
    	 *					}
    	 *					new config container';
    	 * 
    	 * *** remove active class then append new tab button
    	 * 
    	*/
    	$('li.active').removeClass('active');
    	
    	$('#navigation').append('<li class="active"><a href="#'+page.name+'Tab" data-toggle="pill"><span>'+page.title+'</span></a></li>');
    	$('.tab-pane.active').removeClass('active');
    	$('.tab-content').append(
'<div class="tab-pane active" id="'+page.name+'Tab">'+
'<div class="main-content-container">'+
'<div class="main-content">'+
'caca'+ data.contentId +
      '<p>'+
		'<a data-toggle="modal" class="btn btn-warning" href="#config-'+page.name+'"><span class="glyphicon glyphicon-cog"></span> Config page</a> '+
		'<a class="btn btn-danger" href="#"><span class="glyphicon glyphicon-trash"></span> Delete</a>'+
	  '</p>'+
	'<div class="single-content row-fluid" id="'+ page.name +'Content">'+

		'<div class="col-md-6">'+
                      		'<div class="panel panel-info new">'+
                       			'<div class="panel-heading" style="position : relative; overflow:hidden;">Title'+
									'<a href="#" class="edit-pencil"><span class="glyphicon glyphicon-pencil" style="position: absolute; right: 20px; top: -20px;"></span></a>'+
	               				'</div>'+
                      			'<div class="panel-body">'+
           							'<div class="changeable editable" data-toggle="manual" data-name="title" data-type="text" data-pk="'+data.contentId+'" data-url="/page/editable">Edit this Title</div>'+
                                '</div>'+
                        	'</div>'+
                        	'<div class="panel panel-info new">'+
                        		'<div class="panel-heading" style="position : relative; overflow:hidden;">Text'+
         							'<a href="#" class="edit-pencil"><span class="glyphicon glyphicon-pencil" style="position: absolute; right: 20px; top: -20px;"></span></a>'+
								'</div>'+
                        		'<div class="panel-body">'+
                                	'<div class="changeable editable" data-toggle="manual" data-name="text" data-type="textarea" data-pk="'+data.contentId+'" data-url="/page/editable">Edit this Text</div>'+ 
                                '</div>'+
   							'</div>'+
   		'</div>'+
	
     	'<div class="col-md-6">'+
                       '<div class="panel panel-info new">'+
							'<div class="panel-heading" style="position : relative; overflow:hidden;">Image'+
 		                   		'<span style="position: absolute; right: 20px; top: -20px;" class="glyphicon glyphicon-pencil"></span>'+
							'</div>'+
                            '<div class="panel-body">'+
                                '<img class="col-md-12" src="../img/">'+
               				'</div>'+
         		       '</div>'+
         		       
               

     	'</div>'+                
	'</div>'+
'</div>'+                           
'</div>'+
'</div>');

	$(".panel-info.new").hover(function(){
	$(".glyphicon-pencil", this).stop().animate({top:"30%"},{queue:false,duration:100});
	}, function() {
	$(".glyphicon-pencil", this).stop().animate({top:"-20px"},{queue:false,duration:200});
	});
	$('.edit-pencil').click(function(e) {
    var target = $(this).parent().next('.panel-body');
    	e.stopPropagation();
        e.preventDefault();
        target.children('.changeable').editable('toggle');
   	});
   	
   	
    	
    	} else if(data && data.errors){
    	//server-side validation error, response like {"errors": {"username": "username already exist"} }
    	config.error.call(this, data.errors);
    	}
    	},
    	error: function(errors) {
    	var msg = '';
    	if(errors && errors.responseText) { //ajax error, errors = xhr object
    	msg = errors.responseText;
    	} else { //validation error (client-side or server-side)
    	$.each(errors, function(k, v) { msg += k+": "+v+"<br>"; });
    	}
    	$('#msg').removeClass('alert-success').addClass('alert-error').html(msg).show();
    	}
    	});
    });
	$('#addPage').on('hidden.bs.modal', function () {
	 // clear x-editable values
		$('.add-page').editable('setValue', null) //clear values
			.editable('option', 'pk', null) //clear pk
			.removeClass('editable-unsaved'); //remove bold css
		$('#addPage').find('.template').removeClass('editable-empty').empty().editable('setValue', 1);
		$('#add-page').show();
		$('#msg').hide(); 
	})
	
	$('.edit-pencil').click(function(e) {
    var target = $(this).parent().next('.panel-body');
    	e.stopPropagation();
        e.preventDefault();
        target.children('.changeable').editable('toggle');
   	});
   	
   		$(".panel-info").hover(function(){
		$(".glyphicon-pencil", this).stop().animate({top:"30%"},{queue:false,duration:100});
	}, function() {
		$(".glyphicon-pencil", this).stop().animate({top:"-20px"},{queue:false,duration:200});
	});
		
		$.fn.editable.defaults.mode = 'inline';
    	

    	
    	//$('.changeable').editable();
    	
    	

		$("ul.nav").sortable();

})
</script>


</body>

</html>

