
<?php print_r($pages);?>

<ul id="myTab" class="nav nav-tabs">

<?php foreach ($test as $tab) : ?>
 <li><a href="#<?php echo $this->escapeHtml($tab->name);?>" data-toggle="tab"><?php echo $this->escapeHtml($tab->title);?></a></li>
 
<?php endforeach; ?>
</ul>

<div class="tab-content">
	
<?php foreach($pages as $page) {
	
echo'<div class="tab-pane" id="'.$page['name'].'">' ;
	                
                	if($page['carouselCount'] == 1)
					{
				echo '<div class="singleContent">
				          <img src="http://site.jj/img/'.$page['contents'][0]['img'].'" alt="" />
				          <div class="text-caption">
                		      <h4>'.$page['contents'][0]['title'].'</h4>
                      			<p>'.$page['contents'][0]['text'].'</p>
        		          </div>
        		      </div>
						';
					}else{
			echo '<div id="'.$page['name'].'Carousel" class="carousel slide">
                <ol class="carousel-indicators">';
                	
                	 $carouselCount = 0;
							while($carouselCount <= $page['carouselCount'])
					{
						if($carouselCount == 0)
						{
					echo '<li data-target="#'.$this->escapeHtml($page['name']).'Carousel" data-slide-to="'.$carouselCount.'" class="active"></li>'.PHP_EOL ;
					
					
					
						}else{
					echo '<li data-target="#'.$this->escapeHtml($page['name']).'Carousel" data-slide-to="'.$carouselCount.'"></li>'.PHP_EOL ;					
						}
					$carouselCount++;
					
					};
					
							

          echo'   </ol>
                <div class="carousel-inner">';
                
                
                	
                	$contentCount = 0;

					
					
                	 foreach ($page['contents'] as $content) { 
            if($contentCount == 0)
					 {
			echo '<div class="item active">
                  	<img src="http://site.jj/img/'.$this->escapeHtml($content['img']).'" alt="">
                    <div class="carousel-caption">
                      <h1>'.$this->escapeHtml($content['title']).'</h1>
                      <h2>'.$this->escapeHtml($content['label']).'</h2>
                      <p>'.$this->escapeHtml($content['text']).'</p>
                    </div>
                  </div>';
					 }elseif($contentCount >= 1)
					 {
			echo '<div class="item">
                  	<img src="http://site.jj/img/'.$this->escapeHtml($content['img']).'" alt="">
                    <div class="carousel-caption">
                      <h4>'.$this->escapeHtml($content['label']).'</h4>
                      <p>'.$this->escapeHtml($content['text']).'</p>
                    </div>
                  </div>';
				  	 }		 	
					$contentCount++;
					 }	
					
 
          echo '</div>
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
</div>';
}
}?>
</div>
<!--
<script>
$(function () {
$('#myTab a:first').tab('show');
})
</script>-->