
<!DOCTYPE html>
<html>
<head>

<title>img upload</title>

<link href="http://site.jj/bootstrap/bootstrap-3.0.0/dist/css/bootstrap.css" media="screen" rel="stylesheet" type="text/css"/>

<link href="http://site.jj/bootstrap/bootstrap-3.0.0/dist/css/bootstrap-theme.min.css" media="screen" rel="stylesheet" type="text/css"/>



<link rel="stylesheet" type="text/css" href="http://site.jj/bootstrap-editable/css/bootstrap-editable.css"/>

<link rel="stylesheet" type="text/css" href="http://site.jj/css/bootstrap-fileupload.css"/>


<style type="text/css">
.uploader
{
	margin-top: 6px;
	margin-bottom:6px;
}
.preview-youtube-player-container
{
	margin-left:auto;
	margin-right:auto;
}
.no-youtube-video-default
{
	margin-left:auto;
	margin-right:auto;
}
</style>

</head> 
<body>
<div class="container">

<div class="fileupload fileupload-new" data-provides="fileupload">
  <div class="fileupload-new thumbnail" style="width: 400px; height: 350px;">
	<img src="http://www.placehold.it/400x350/EFEFEF/AAAAAA&text=no+image" />
  </div>
  <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 400px; max-height: 350px; line-height: 20px;">
  </div>
  <div class="media-youtube-exists"></div>

<div>
  	
  	<a href="#" class="btn btn-primary btn-sm save-image-upload fileupload-exists">
		<i class="glyphicon glyphicon-ok"></i>
	</a>

    <a href="#" class="btn btn-default btn-sm fileupload-exists" data-dismiss="fileupload">
    	<i class="glyphicon glyphicon-remove"></i>
    </a>
  <div class="row">  	
<form enctype="multipart/form-data" method="post">
   <span class="uploader btn btn-sm btn-primary btn-file">
    <span class="fileupload-new">Select image <i class="glyphicon glyphicon-picture"></i></span>
    <span class="fileupload-exists">Change</span>
<input id="imageupload" name="files" type="file" />
   </span>
</form>
<a href="#" class="btn btn-primary btn-sm embed-media" data-toggle="modal" data-pk="5" data-target="#embedMedia">Embed New Media <i class="glyphicon glyphicon-film"></i></a>
  </div>

</div>
 
  
 
</div>

<!-- Modal -->
<div class="modal fade" id="embedMedia" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <div class="modal-body">
        <input id="embed-input" class="form-control" placeholder="Embed Url" required="" autofocus="" type="text">
	<button type="button" id="check-url" class="btn btn-success btn-sm">check</button>
       <br />
       <fieldset disabled>
        <select id="disabledSelect" class="form-control">
        	<option>Youtube</option>
      	</select>
       </fieldset>
       <br />
       <div id="preview-youtube-player-container"></div>
       	<p class="preview-youtube-player-container-no-video">
       	<img class="thumbnail no-youtube-video-default" src="http://www.placehold.it/300x200/EFEFEF/AAAAAA&text=no+Youtube+video" />
       	</p>
  	   
  	   
  	   <br />
        <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">
        	<i class="glyphicon glyphicon-remove"></i>
        </button>
        <button type="button" id="update-embed" class="btn btn-success btn-sm">
        	<i class="glyphicon glyphicon-ok"></i>
        </button>
      </div>
      
        
     
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="msg"></div>

<div id='youtube-player-container' data-url="Yj6nqPeGaoE"></div> 	

</div>

<script src="http://code.jquery.com/jquery-2.0.3.js"></script>
<script src="http://site.jj/js/bootstrap.min.js"></script>

<script src="http://site.jj/bootstrap/bootstrap-3.0.0/js/modal.js"></script>
<script src="http://site.jj/bootstrap-editable/js/bootstrap-editable.js"></script>

<script src="http://blueimp.github.io/jQuery-File-Upload/js/vendor/jquery.ui.widget.js"></script>
<script src="http://blueimp.github.io/jQuery-File-Upload/js/jquery.iframe-transport.js"></script>
<script src="http://blueimp.github.io/jQuery-File-Upload/js/jquery.fileupload.js"></script>
<script src="http://site.jj/js/bootstrap-fileupload.js"></script>
<script src="/js/jQuery.tubeplayer.js"></script>
<script>
$(document).ready(function() {

/**
 * JavaScript function to match (and return) the video Id 
 * of any valid Youtube Url, given as input string.
 * @author: Stephan Schmitz <eyecatchup@gmail.com>
 * @url: http://stackoverflow.com/a/10315969/624466
 */
function ytVidId(url) {
  var p = /^(?:https?:\/\/)?(?:www\.)?(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|watch\?v=|watch\?.+&v=))((\w|-){11})(?:\S+)?$/;
  return (url.match(p)) ? RegExp.$1 : false;
}

$("body").on('change.bs.fileinput', function () {
	
$(".media-youtube-exists").hide();
$('.fileupload-preview.fileupload-exists.thumbnail').show();
	
	
});

$('.save-image-upload').click(function(){

	
    var file_data = $("#imageupload").prop("files")[0];   // Getting the properties of file from file field
    var form_data = new FormData();                  // Creating object of FormData class
    form_data.append("file", file_data)              // Appending parameter named file with properties of file_field to form_data
    form_data.append("pk", 5)                 // Adding extra parameters to form_data
    $.ajax({
                url: "http://site.jj/page/stage-example",
                dataType: 'json',
                cache: false,
                contentType: false,
                processData: false,
                data: form_data,                         // Setting the data attribute of ajax with file_data
                type: 'post'
       });




});

$('.embed-media').click(function (e){

	
	var pk = $(this).data('pk');
	
	$('#embedMedia').on('show.bs.modal', function () {

	$('#check-url').click(function(){
	
	var video = 0;
	
	var url = $('#embed-input').val();
		
	var video = ytVidId(url);
	
	

	$('.preview-youtube-player-container-no-video').hide();
	
	$('#preview-youtube-player-container').tubeplayer('destroy');
	
	$('#preview-youtube-player-container').tubeplayer({
	allowFullScreen: "true", // true by default, allow user to go full screen
	initialVideo: video,
	});

	
	
	//$('#preview-youtube-player-container').tubeplayer({"cue": video});
	
	});

		$('#update-embed').click(function(){
			var embed_update = $('#embed-input').val();
			var video = ytVidId(embed_update);
			var data = {};
			data['url'] = video;
			data['pk'] = pk;
			data['kind'] = 'youtube';
			$.ajax({
				url: "http://site.jj/page/embed-media",
                dataType: 'json',
                data: data,                         // Setting the data attribute of ajax with file_data
                type: 'post',
                complete: function(data, config){
                	
                	$('.fileupload-new.thumbnail').hide();
                	$('.fileupload-preview.fileupload-exists.thumbnail').hide();
                	
                	
                	$('.media-youtube-exists').tubeplayer('destroy');

               		$('.media-youtube-exists').tubeplayer({allowFullScreen: "true",initialVideo: video});
               		//$('.media-youtube-exists').tubeplayer({play:video});
              
                },
			});
		});
	});
});

//$(".youtube-player-container").load(function(e) {
// Handler for .load() called.

//var url = $(this).data('url');

/*if(){
$(this).tubeplayer({
	width: 600, // the width of the player
	height: 450, // the height of the player
	allowFullScreen: "true", // true by default, allow user to go full screen
	initialVideo: "Yj6nqPeGaoE", // the video that is loaded into the player
	preferredQuality: "default",// preferred quality: default, small, medium, large, hd720
	onPlay: function(id){}, // after the play method is called
	onPause: function(){}, // after the pause method is called
	onStop: function(){}, // after the player is stopped
	onSeek: function(time){}, // after the video has been seeked to a defined point
	onMute: function(){}, // after the player is muted
	onUnMute: function(){} // after the player is unmuted
});
}else if()
{
	
}
*/
//});



});

</script>

<form>
  <input id="target" type="text" value="Field 1">
  <input type="text" value="Field 2">
</form>
<div id="other">
  Trigger the handler
</div>
The event handler can be bound to the first input field:
<script>$( "#target" ).blur(function() {
  alert( "Handler for .blur() called." );
});
</script>

</body>
</html>
