
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

        <title>Mingus Control Panel</title>

        <!-- Bootstrap core CSS -->
        <link href="/css/bootstrap.css" media="screen" rel="stylesheet" type="text/css">
        <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
        <link href="/css/controlpanel.css" media="screen" rel="stylesheet" type="text/css">

        <!-- Just for debugging purposes. Don't actually copy this line! -->
        <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>

        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">

                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a class="navbar-brand" href="/">Mingus</a>

                </div>

                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="/user">Home</a></li>
                        <li><a href="/page">Edit content</a></li>
                        <li><a href="<?php echo $this->url('zfcuser/changeemail') ?>">Change email</a></li>
                        <li><a href="<?php echo $this->url('zfcuser/changepassword') ?>">Change password</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="<?php echo $this->url('zfcuser/logout') ?>" id="logout-btn"><i style="font-size:18px" class="fa fa-sign-out push-right"></i></a></li>
                        <li><a href="<?php echo $this->url('zfcuser/logout') ?>" id="logout-btn"><i style="font-size:18px" class="fa fa-plus push-right"></i></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>


        <?php echo $this->content; ?>




        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script type="text/javascript" src="http://code.jquery.com/jquery-2.1.0.js"></script>

        
        <script type="text/javascript" src="/js/bootstrap.js"></script>

        <script type="text/javascript" src="/bootstrap/bootstrap-3.0.0/js/collapse.js"></script>
        <script type="text/javascript" src="/bootstrap/bootstrap-3.0.0/js/modal.js"></script>
        <script type="text/javascript" src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
        <!--[if lt IE 9]><script type="text/javascript" src="/js/html5.js"></script><![endif]-->

        <script type="text/javascript" src="/bootstrap-editable/js/bootstrap3-editable.js"></script>

        <script src="http://blueimp.github.io/jQuery-File-Upload/js/vendor/jquery.ui.widget.js"></script>
        <script src="http://blueimp.github.io/jQuery-File-Upload/js/jquery.iframe-transport.js"></script>
        <script src="http://blueimp.github.io/jQuery-File-Upload/js/jquery.fileupload.js"></script>
        <script src="/js/bootstrap-fileupload.js"></script>

        <script type="text/javascript">
            $(document).ready(function() {
                $('#control-panel a:first').tab('show');

                $('#add-carousel-title').editable();

                $('.template').editable({
                    url: '/page/save',
                    value: 1,
                    source: [
                        {value: 1, text: 'Single Page'},
                        {value: 2, text: 'Carousel Page'},
                        {value: 3, text: 'Custom Page'}
                    ]
                });

                $('.add-page').editable({
                    url: '/page/save' //this url will not be used for cxreating new user, it is only for update
                });
                $('.changeable-page').editable({
                    url: '/page/save'
                });
                $('.template').editable({
                    url: '/page/save'
                });

                $('#add-page').click(function() {
                    $('.add-page').editable('submit', {
                        url: '/page/add',
                        ajaxOptions: {
                            dataType: 'json' //assuming json response
                        },
                        success: function(data, config) {
                            if (data && data.id) { //record created, response like {"id": 2}
                                //set pk
                                $(this).editable('option', 'pk', data.id);
                                //remove unsaved class
                                $(this).removeClass('editable-unsaved');
                                //show messages
                                var msg = 'New Page created! Now submit individually.';
                                $('#msg').addClass('alert-success').removeClass('alert-error').html(msg).show();
                                $('#add-page').hide();
                                $(this).off('save.newuser');
                                var page = $(this).editable('getValue');
                                alertMsg = 'this is the name:' + page.name + ' this is the title:' + page.title + ' and this is the tmplate number:' + page.template;
                                alert(alertMsg);
                                /* 
                                 *$('.blablabla').append()
                                 *var newTabHTML =   'new tab button done
                                 *					new empty tab container{
                                 *					new config button I.E. edit and delete
                                 *					}
                                 *					new config container';
                                 * 
                                 * *** remove active class then append new tab button
                                 * 
                                 */

                                if (page.template == 1) {



                                    $('li.active').removeClass('active');

                                    $('#navigation').append('<li class="active"><a href="#' + page.name + 'Tab" data-toggle="pill"><span>' + page.title + '</span></a></li>');
                                    $('.tab-pane.active').removeClass('active');
                                    $('.tab-content').append(
                                            '<div class="tab-pane active" id="' + page.name + 'Tab">' +
                                            '<div class="main-content-container">' +
                                            '<div class="main-content">' +
                                            'contentId:' + data.contentId +
                                            '<p>' +
                                            '<a data-toggle="modal" class="btn btn-warning" href="#config-' + page.name + '"><span class="glyphicon glyphicon-cog"></span> Config page</a> ' +
                                            '<a class="btn btn-danger delete-page" href="#" data-pk="' + data.id + '"><span class="glyphicon glyphicon-trash"></span> Delete</a>' +
                                            '</p>' +
                                            '<div class="single-content row-fluid" id="' + page.name + 'Content">' +
                                            '<div class="col-md-6">' +
                                            '<div class="panel panel-info new">' +
                                            '<div class="panel-heading" style="position : relative; overflow:hidden;">Title' +
                                            '<a href="#" class="edit-pencil"><span class="glyphicon glyphicon-pencil" style="position: absolute; right: 20px; top: -20px;"></span></a>' +
                                            '</div>' +
                                            '<div class="panel-body">' +
                                            '<div class="changeable editable" data-toggle="manual" data-name="title" data-type="text" data-pk="' + data.contentId + '" data-url="/page/editable">Edit this Title</div>' +
                                            '</div>' +
                                            '</div>' +
                                            '<div class="panel panel-info new">' +
                                            '<div class="panel-heading" style="position : relative; overflow:hidden;">Text' +
                                            '<a href="#" class="edit-pencil"><span class="glyphicon glyphicon-pencil" style="position: absolute; right: 20px; top: -20px;"></span></a>' +
                                            '</div>' +
                                            '<div class="panel-body">' +
                                            '<div class="changeable editable" data-toggle="manual" data-name="text" data-type="textarea" data-pk="' + data.contentId + '" data-url="/page/editable">Edit this Text</div>' +
                                            '</div>' +
                                            '</div>' +
                                            '</div>' +
                                            '<div class="col-md-6">' +
                                            '<div class="panel panel-info new">' +
                                            '<div class="panel-heading" style="position : relative; overflow:hidden;">Image' +
                                            '<span style="position: absolute; right: 20px; top: -20px;" class="glyphicon glyphicon-pencil"></span>' +
                                            '</div>' +
                                            '<div class="panel-body">' +
                                            '<img class="col-md-12" src="../img/">' +
                                            '</div>' +
                          '</div>' +
                                            '</div>' +
                                            '</div>' +
                                            '</div>' +
                                            '</div>' +
                                            '</div>');

                                    $('#modalContainer').append(
                                            '<div class="modal fade edit-page" id="config-' + page.name + '" tabindex="-1" role="dialog"  aria-hidden="true">' +
                                            '<div class="modal-dialog">' +
                                            '<div class="modal-content">' +
                                            '<div class="modal-header">' +
                                            '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>' +
                                            '<h4 class="modal-title">Config page</h4>' +
                                            '</div>' +
                                            '<div class="modal-body">' +
                                            '<table  class="table table-bordered table-striped">' +
                                            '<tbody>' +
                                            '<tr>' +
                                            '<td width="40%">Page Title (Title in the Tabs)</td>' +
                                            '<td><a href="#" class="changeable-page editable editable-click" data-pk="' + data.id + '" data-type="text" data-name="title">' + page.title + '</a></td>' +
                                            '</tr>' +
                                            '<tr>' +
                                            '<td>Page Name (in one word)</td>' +
                                            '<td><span style="color:grey">' + page.name + '</span></td>' +
                                            '</tr>' +
                                            '<tr>' +
                                            '<td>Choose page Template</td>' +
                                            '<td><a href="#" class="template changeable-page editable editable-click" data-pk="' + data.id + '" data-type="select" data-name="template" data-value="' + page.template + '"></a></td>' +
                                            '</tr>' +
                                            '</tbody>' +
                                            '</table>' +
                                            '</div>' +
                                            '<div class="modal-footer">' +
                                            '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>' +
                                            '</div>' +
                                            '</div>' +
                                            '</div>' +
                                            '</div>');

                                    $('.template').editable({
                                        source: [
                                            {value: 1, text: 'Single Page'},
                                            {value: 2, text: 'Carousel Page'},
                                            {value: 3, text: 'Custom Page'}
                                        ]
                                    })

                                    $('.delete-page').click(function(e) {
                                        var pk = $(this).data('pk');
                                        var request = {};
                                        request['pk'] = pk;
                                        $.ajax({
                                            url: "/page/delete-page",
                                            dataType: 'json',
                                            data: request, // Setting the data attribute of ajax with file_data
                                            type: 'post',
                                            complete: function() {
                                                window.location.reload();
                                            },
                                        });


                                    });



                                    $(".panel-info.new").hover(function() {
                                        $(".glyphicon-pencil", this).stop().animate({top: "30%"}, {queue: false, duration: 100});
                                    }, function() {
                                        $(".glyphicon-pencil", this).stop().animate({top: "-20px"}, {queue: false, duration: 200});
                                    });
                                    $('.edit-pencil').click(function(e) {
                                        var target = $(this).parent().next('.panel-body');
                                        e.stopPropagation();
                                        e.preventDefault();
                                        target.children('.changeable').editable('toggle');
                                    });
                                } else if (page.template == 2) {


                                    $('#addPage').modal('hide');
                                    $('#addPage').on('hidden.bs.modal', function() {
                                        $('#carouselTitle').modal('show');
                                        $('#save-add-carousel-title').click(function() {
                                            $('#add-carousel-title').editable('submit', {
                                                url: '/page/update-carousel-title',
                                                ajaxOptions: {
                                                    dataType: 'json', //assuming json response

                                                },
                                                data: {name: page.name},
                                                success: function(data, config) {
                                                    alert('succes!!')
                                                }
                                            });
                                        });
                                        $('#carouselTitle').on('hidden.bs.modal', function() {
                                            window.location.reload();
                                        });

                                    });


                                } else if (page.template == 3) {
                                    window.location.reload();
                                }


                            } else if (data && data.errors) {
                                //server-side validation error, response like {"errors": {"username": "username already exist"} }
                                config.error.call(this, data.errors);
                            }
                        },
                        error: function(errors) {
                            var msg = '';
                            if (errors && errors.responseText) { //ajax error, errors = xhr object
                                msg = errors.responseText;
                            } else { //validation error (client-side or server-side)
                                $.each(errors, function(k, v) {
                                    msg += k + ": " + v + "<br>";
                                })
                                        ;
                            }
                            $('#msg').removeClass('alert-success').addClass('alert-error').html(msg).show();
                        }
                    }); //editable submit
                }); // on #add-page click

                $('#addPage').on('hidden.bs.modal', function() {
                    // clear x-editable values
                    $('.add-page').editable('setValue', null) //clear values
                            .editable('option', 'pk', null) //clear pk
                            .removeClass('editable-unsaved'); //remove bold css
                    $('#addPage').find('.template').removeClass('editable-empty').empty().editable('setValue', 1);
                    $('#add-page').show();
                    $('#msg').hide();
                });

                $('.edit-page').on('hidden.bs.modal', function() {
                    window.location.reload();
                });

                $(".media-edit-buttons").hide();

                $('.edit-pencil').click(function(e) {
                    var panel = $(this).parent().next('.panel-body');
                    var mediaEdit = panel.find('.media-edit-buttons');
                    e.stopPropagation();
                    e.preventDefault();

                    if ($(this).data('type') == 'img') {

                        mediaEdit.show();


                    } else {
                        panel.children('.changeable').editable('toggle');
                    }




                });

                $("body").click(function() {
                    $('.media-edit-buttons').hide();
                });

                //	$(".media-edit-buttons").focusout(function(e) {
                //	$(this).hide();
                //});

                $(".panel-info").hover(function() {
                    $(".glyphicon-pencil", this).stop().animate({top: "30%"}, {queue: false, duration: 100});
                }, function() {
                    $(".glyphicon-pencil", this).stop().animate({top: "-20px"}, {queue: false, duration: 200});
                });

                $.fn.editable.defaults.mode = 'inline';



                //$('.changeable').editable();



                $("ul.nav").sortable({
                    update: function(event, ui) {

                        //var result = $(event.target).sortable("toArray", {attribute: "data-pk"});
                        var result = $(event.target).sortable("serialize", {attribute: "data-pk"});
                        //var numbers = result.replace(/page_/g, '');

                        alert(result);
                        $.ajax({
                            url: "/page/sortable-page",
                            dataType: 'json',
                            data: result, // Setting the data attribute of ajax with file_data
                            type: 'post',
                        });

                    }});
                $('.delete-page').click(function(e) {
                    var pk = $(this).data('pk');
                    var request = {};
                    request['pk'] = pk;
                    $.ajax({
                        url: "/page/delete-page",
                        dataType: 'json',
                        data: request, // Setting the data attribute of ajax with file_data
                        type: 'post',
                        complete: function() {
                            window.location.reload();
                        },
                    });


                });

                $('.reload').click(function() {
                    window.location.reload();  //should be a dynamic remove action on jquery part
                });

                $('#updateCarouselTitle').editable({
                    url: '/page/update-carousel-title'
                });

                $('#addCarouselLabel').editable();


                $('.add-carousel-btn').click(function(e) {
                    var pageName = $(this).data('page');
                    //alert(pageName);

                    //$('#addCarouselTitle').attr('data-pagename', pageName);

                    $('#addCarouselModal').modal('show');

                    $('#add-carousel').click(function(e) {

                        var carousel = $('#addCarouselLabel').editable('getValue');

                        /*	var request = {};
                         request['title'] = carousel;
                         request['name']	=pageName;
                 
                 
                         $.ajax({
                         url: "/page/add-carousel",
                         dataType: 'json',
                         data: request,                         // Setting the data attribute of ajax with file_data
                         type: 'post',
                         complete: function(){
                         */
                        $('#addCarouselLabel').editable('submit', {
                            url: '/page/add-carousel',
                            ajaxOptions: {
                                dataType: 'json', //assuming json response   		
                            },
                            data: {name: pageName},
                            success: function(data, config) {
                                if (data && data.id) { //record created, response like {"id": 2, }

                                    alert(data.id);

                                    //set pk
                                    $(this).editable('option', 'pk', data.id);
                                    //remove unsaved class
                                    $(this).removeClass('editable-unsaved');
                                    //show messages
                                    //var msg = 'New Page created! Now submit individually.';
                                    //$('#msg').addClass('alert-success').removeClass('alert-error').html(msg).show();
                                    //$('#add-carousel').hide();

                                    //var carousel = $(this).editable('getValue');
                                    //var pageName = $(this).data('name');

                                    var panelGroup = pageName + 'Carousel';

                                    $('#' + panelGroup).append('  <div class="panel panel-default" data-pk="' + data.id + '">' +
                                            '<div class="panel-heading">' +
                                            '<h4 class="panel-title">' +
                                            '<a class="accordion-toggle" data-toggle="collapse" data-parent="#' + pageName + 'Carousel" href="#carousel-edit-' + data.id + '">' +
                                            carousel.label +
                                            '</a>' +
                                            '</h4>' +
                                            '</div>' +
                                            '<div id="carousel-edit-' + data.id + '" class="panel-collapse collapse">' +
                                            '<div class="panel-body">' +
                                            '<div class="col-md-6">' +
                                            '<div class="panel panel-info">' +
                                            '<div class="panel-heading" style="position : relative; overflow:hidden;">' +
                                            'Label' +
                                            '<a href="#" class="edit-pencil"><span class="glyphicon glyphicon-pencil" style="position : absolute; right : 20; top :-20px;"></span></a>' +
                                            '</div>' +
                                            '<div class="panel-body">' +
                                            '<div class="changeable" data-toggle="manual" data-name="label" data-type="text" data-pk="' + data.id + '" data-url="/page/editable">' +
                                            '</div>' +
                                            '</div>' +
                                            '</div>' +
                                            '<div class="panel panel-info">' +
                                            '<div class="panel-heading" style="position : relative; overflow:hidden;">' +
                                            'Text' +
                                            '<a href="#" class="edit-pencil"><span class="glyphicon glyphicon-pencil" style="position : absolute; right : 20; top :-20px;"></span></a>' +
                                            '</div>' +
                                            '<div class="panel-body">' +
                                            '<div class="changeable" data-toggle="manual" data-name="text" data-type="textarea" data-pk="' + data.id + '" data-url="/page/editable">' +
                                            '</div>' +
                                            '</div>' +
                                            '</div>' +
                                            '</div>' +
                                            '<div class="col-md-6">' +
                                            '<div class="panel panel-info">' +
                                            '<div class="panel-heading" style="position : relative; overflow:hidden;">' +
                                            'Image' +
                                            '<a href="#" class="edit-pencil"><span class="glyphicon glyphicon-pencil" style="position : absolute; right : 20; top :-20px;"></span></a>' +
                                            '</div>' +
                                            '<div class="panel-body">' +
                                            '<div class="thumbnail">' +
                                            '<img src="http://www.placehold.it/400x350/EFEFEF/AAAAAA&text=no+image" alt="">' +
                                            '</div>' +
                                            '</div>' +
                                            '</div>' +
                                            '</div>' +
                                            '</div>' +
                                            '</div>' +
                                            '</div>');
                                }//end of if(data && ...)
                            }// end of succes

                        }); //end of editable submit

                        /*
                         $.ajax({
                         url: "/page/add-content",
                         dataType: 'json',
                         data: request,                         // Setting the data attribute of ajax with file_data
                         type: 'post',
                         complete: function(){
                         */





                    }); // on click

                    $('#addCarouselModal').on('hidden.bs.modal', function() {
                        // clear x-editable values
                        $('#addCarouselLabel').editable('setValue', 'Blank Label') //clear values
                                .editable('option', 'pk', null); //clear pk

                    });

                });

                $('.carousel-title').editable();



                $('.deletable-button').click(function(e) {
                    var pk = $(this).parent().parent().parent().data('pk');


                    var request = {};
                    request['pk'] = pk;
                    $.ajax({
                        url: "/page/delete-content",
                        dataType: 'json',
                        data: request, // Setting the data attribute of ajax with file_data
                        type: 'post',
                        complete: function() {
                            window.location.reload();
                        },
                    });

                });



                //Media embed

                function ytVidId(url) {
                    var p = /^(?:https?:\/\/)?(?:www\.)?(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|watch\?v=|watch\?.+&v=))((\w|-){11})(?:\S+)?$/;
                    return (url.match(p)) ? RegExp.$1 : false;
                }

                $('.save-image-upload').click(function(e) {
                    var pk = $(this).data('pk');

                    var file_data = $(this).parent().find(".imageupload").prop("files")[0];//$(".imageupload").prop("files")[0];   // Getting the properties of file from file field
                    var form_data = new FormData();                  // Creating object of FormData class
                    form_data.append("file", file_data);              // Appending parameter named file with properties of file_field to form_data
                    form_data.append("pk", pk);                 // Adding extra parameters to form_data
                    $.ajax({
                        url: "/page/stage-example",
                        dataType: 'json',
                        cache: false,
                        contentType: false,
                        processData: false,
                        data: form_data, // Setting the data attribute of ajax with file_data
                        type: 'post'
                    });

                    $(".imageupload").empty();



                });

                $('.embed-media').click(function(e) {


                    var pk = $(this).data('pk');

                    $('#embedMedia').on('show.bs.modal', function() {

                        $('#check-url').click(function() {

                            var video = 0;

                            var url = $('#embed-input').val();

                            var video = ytVidId(url);



                            $('.preview-youtube-player-container-no-video').remove();

                            $('.preview-youtube-player-container').tubeplayer('destroy');

                            $('.preview-youtube-player-container').tubeplayer({
                                allowFullScreen: "true", // true by default, allow user to go full screen
                                initialVideo: video,
                            });

                        });

                        $('#update-embed').click(function() {
                            var embed_update = $('#embed-input').val();
                            var video = ytVidId(embed_update);
                            var data = {};
                            data['url'] = video;
                            data['pk'] = pk;
                            data['kind'] = 'youtube';
                            $.ajax({
                                url: "/page/embed-media",
                                dataType: 'json',
                                data: data, // Setting the data attribute of ajax with file_data
                                type: 'post',
                                complete: function(data, config) {




                                },
                            });
                        });
                    });
                });

                $(".youtube-player-container").load(function(e) {
        // Handler for .load() called.

                    var url = $(this).data('url');

                    /*if(){
                     $(this).tubeplayer({
                     width: 600, // the width of the player
                     height: 450, // the height of the player
                     allowFullScreen: "true", // true by default, allow user to go full screen
                     initialVideo: "Yj6nqPeGaoE", // the video that is loaded into the player
                     preferredQuality: "default",// preferred quality: default, small, medium, large, hd720
                     onPlay: function(id){}, // after the play method is called
                     onPause: function(){}, // after the pause method is called
                     onStop: function(){}, // after the player is stopped
                     onSeek: function(time){}, // after the video has been seeked to a defined point
                     onMute: function(){}, // after the player is muted
                     onUnMute: function(){} // after the player is unmuted
                     });
                     }else if()
                     {
             
                     }
                     */
                });

                $('#navigation li').each(function() {
                    if ($(this).hasClass('active')) {
                        var activeLabel = $(this).html();
                        $('.navbar-brand').html(activeLabel);
                    }
                });

                $('#navigation a').click(function() {
                    var label = $(this).html();
                    $('.navbar-brand').html('<a href="#">' + label + '</a>');
                });


            })
        </script>




    </body>
</html>

