<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        
        <!-- Le styles -->
       
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/medicus-corda.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')?>



    </head>
    <body>
        <div class="container">
            <a class="brand" href="<?php echo $this->url('home') ?>">&nbsp;</a>
        </div>

        <div class="container main-content-container">
            <div class="main-content">
            <?php echo $this->content; ?>
            </div>
        </div>
        <div class="container">
            <hr>
            
            <footer>
                <p>&copy; <?php echo date('Y') ?> by medicuscorda.com <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
                <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      //->prependFile($this->basePath() . '/bootstrap/js/bootstrap-carousel.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js');?>
									   
        <?php echo $this->inlineScript() ;?>
    </body>
</html>

